name: Validate Client ID Documents

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-python@v7.0.0
        with:
          python-version: "3.x"
      - uses: extractions/setup-just@v4
      - run: just validate
